### ISSUE TITLE
Check if path is indeed an int before parsing it

### ISSUE THREAD

**Issue by x421** [PullNotifications/PullNotifications#9]
A little followup to #4:

In line ```183``` of ```pn_serven.nim``` (as of writing) the length of the path is checked. For safety reasons it should also check if there is an int or else throw a ```400``` client error.

To keep the code in the request handling clean I would just hand over the whole request to ```getNotifiication``` and parse it there.

Or maybe a new method, ```checkLastURLSegmentIsInt``` before the ```case```, we could reuse that later on.

**Comment by mrbandler** [comment]
Good ideas, keeps code cleaner along the way.
